Update bcftools filter cmd
phac-nml/snvphyl-tools pull request #1
Opened 2019-05-21 20:25 UTC by Takadonet

Update bcftools filter command so it will be compliant for bcftools version 1.9+

Had to update test for rearrange_snv_matrix.pl due to changes of sorting by default alphabetically with leaf node with same value.

2019-05-23 15:50 UTC, apetkau requested changes
This is awesome @Takadonet. Thanks so much for updating everything. I got all the tests to pass.

A few comments:

1. Can you update the `CHANGELOG.md` to add your specific changes (should it be release `1.8.2`. or `1.9`?)
2. Since this is meant to update the code to work with **bcftools** `1.9+`, could you update the `install_deps.sh` script to install this version of bcftools/other libraries? And could you update the `README.md` file so it does not mention version `1.5` anymore?

2019-05-27 16:16 UTC, apetkau requested changes
Thanks @Takadonet this looks great. However, I was having an issue with the tests. The script `install_deps.sh` does not install `samtools`, which was causing issues.

I believe we should either add this to `install_deps.sh`, or just mention in the `README.md` file to install `samtools` version 1.9.

2019-05-27 16:16 UTC, apetkau commented on README.md
>  PERL5LIB=/home/test/snvphyl-tools/lib/perl5
I think this needs to be `export PERL5LIB` here.

2019-05-27 17:28 UTC, Takadonet commented on README.md
>  PERL5LIB=/home/test/snvphyl-tools/lib/perl5
Fixed

2019-05-27 17:52 UTC, apetkau approved these changes

2019-05-27 17:52 UTC, apetkau commented
Looks good. Thanks @Takadonet

2019-05-27 17:52 UTC, merged