Ci testing
phac-nml/snvphyl-tools pull request #5
Opened 2019-05-31 13:23 UTC by Takadonet

2019-05-31 21:20 UTC, apetkau requested changes
Looks great. Thanks @Takadonet.

Could you add an entry in the `CHANGELOG.md` saying that you've gotten the integration tests to work in Travis? Maybe version `1.8.3` or `1.9` (Specific version doesn't matter so much).

2019-05-31 21:20 UTC, apetkau commented on install_deps.sh
> +conda install -y perl perl-bioperl perl-hash-merge perl-list-moreutils perl-math-round perl-parallel-forkmanager perl-string-util perl-template-toolkit perl-test-exception perl-text-csv perl-text-dif
Could you add a check here to make sure conda exists? E.g.,

```bash
conda --version 1>/dev/null 2>/dev/null
exit_code = $?
if [ exit_code -ne 0 ]
    echo "Please install 'conda' before continuing.
fi
```

Also, maybe these should be installed in a specific conda environment so that if someone wanted to run the tests locally they wouldn't clutter up their main conda environment?

2019-06-03 12:57 UTC, Takadonet commented on install_deps.sh
> +conda install -y perl perl-bioperl perl-hash-merge perl-list-moreutils perl-math-round perl-parallel-forkmanager perl-string-util perl-template-toolkit perl-test-exception perl-text-csv perl-text-dif
Added check and now creating a new temp env for testing.

2019-06-03 14:35 UTC, apetkau commented
Looks great. Merging.

2019-06-03 14:35 UTC, merged